repos:
-   repo: local
    hooks:
    -   id: increment-version
        name: Increment version number for modified addons
        entry: /home/hmg/Documents/hooks/pythonProject/pre-commit.py
        language: system
        types: [python]